<a href="https://colab.research.google.com/github/Saurabh0888/learning/blob/master/Keras_Learning_1_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [ ]:
file_url= "http://storage.googleapis.com/download.tensorflow.org/data/heart.csv"
df= pd.read_csv(file_url)

In [ ]:
df.shape

(303, 14)

In [ ]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [ ]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [ ]:
df['target'].value_counts()

0    220
1     83
Name: target, dtype: int64

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.594059    0.676568    3.108911  131.785479  246.547855    0.148515   
std      9.016370    0.468560    1.028414   17.748338   52.175933    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    2.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.990099  149.194719    0.326733    1.057756    1.590759    0.683168   
std      0.988293   23.173368    0.469794    1.165025    0.617767    0.937773   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  132.000000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  152.000000    0.000000    0.800000    2.000000    0.000000   
75%      2.000000  165.500000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

           target  
count  303.000000  
mean     0.273927  
std      0.446710  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [ ]:
df_val= df.sample(frac=0.20, random_state= 121)
df_train= df.drop(df_val.index)
print(f'using {len(df_train)} rows for training and {len(df_val)} for validation')

using 242 rows for training and 61 for validation


In [ ]:
def dataframe_to_dataset(dataframe):
  dataframe= dataframe.copy()
  labels= dataframe.pop("target")
  ds= tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  ds= ds.shuffle(buffer_size=len((dataframe)))
  return ds

train_ds= dataframe_to_dataset(df_train)
val_ds= dataframe_to_dataset(df_val)

In [ ]:
### Each Dataset yields a tuple (input, target) where input is a dictionary of features and target is the value 0 or 1.

for x,y in train_ds.take(1):
  print("Input: ", x)
  print("\nTarget" , y)

Input:  {'age': <tf.Tensor: shape=(), dtype=int64, numpy=54>, 'sex': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'cp': <tf.Tensor: shape=(), dtype=int64, numpy=3>, 'trestbps': <tf.Tensor: shape=(), dtype=int64, numpy=108>, 'chol': <tf.Tensor: shape=(), dtype=int64, numpy=267>, 'fbs': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'restecg': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'thalach': <tf.Tensor: shape=(), dtype=int64, numpy=167>, 'exang': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'oldpeak': <tf.Tensor: shape=(), dtype=float64, numpy=0.0>, 'slope': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'ca': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'thal': <tf.Tensor: shape=(), dtype=string, numpy=b'normal'>}

Target tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
train_ds= train_ds.batch(32)
val_ds= val_ds.batch(32)

In [ ]:
x= np.random.sample((20,2))
dataset= tf.data.Dataset.from_tensor_slices(x)
list(dataset.as_numpy_iterator())


[array([0.73076701, 0.41471091]),
 array([0.50158608, 0.95436678]),
 array([0.74758885, 0.76457272]),
 array([0.52530943, 0.88313117]),
 array([0.07368967, 0.93074579]),
 array([0.77149204, 0.06235131]),
 array([0.72722531, 0.4261454 ]),
 array([0.60324236, 0.32847976]),
 array([0.01276759, 0.6055237 ]),
 array([0.18018286, 0.33726996]),
 array([0.11529229, 0.14826794]),
 array([0.37238454, 0.78389857]),
 array([0.33465139, 0.53629086]),
 array([0.97263815, 0.15155125]),
 array([0.25892046, 0.94900038]),
 array([0.58803127, 0.43552666]),
 array([0.55810334, 0.41073205]),
 array([0.38307731, 0.79980659]),
 array([0.2771948 , 0.89514981]),
 array([0.29364725, 0.5428819 ])]

In [ ]:
x= np.random.sample((20,2))
print(x.shape)
x

(20, 2)


array([[0.77816434, 0.23701695],
       [0.54582098, 0.09257507],
       [0.06969471, 0.74333286],
       [0.64474942, 0.16107059],
       [0.47242631, 0.12282739],
       [0.52563349, 0.48188219],
       [0.73004808, 0.08641088],
       [0.90203911, 0.56993756],
       [0.40086622, 0.05414959],
       [0.64623242, 0.19212025],
       [0.00822958, 0.42970018],
       [0.14155148, 0.05145543],
       [0.48971298, 0.67668342],
       [0.31191292, 0.67306423],
       [0.93733772, 0.72988148],
       [0.43771398, 0.40085279],
       [0.19800263, 0.56399919],
       [0.71787798, 0.36365069],
       [0.80420183, 0.47863524],
       [0.79463618, 0.54882554]])